//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlan_Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicPlan_Desktop.Resources.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить/Редактировать расписание.
        /// </summary>
        public static string AddEditSchedule {
            get {
                return ResourceManager.GetString("AddEditSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить расписание этого типа для всех курсов?.
        /// </summary>
        public static string ApplyForAllStudyYears {
            get {
                return ResourceManager.GetString("ApplyForAllStudyYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Концертмейстерские часы.
        /// </summary>
        public static string ConcertMasterParameters {
            get {
                return ResourceManager.GetString("ConcertMasterParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить расписание.
        /// </summary>
        public static string DeleteSchedule {
            get {
                return ResourceManager.GetString("DeleteSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить предмет.
        /// </summary>
        public static string DeleteSubject {
            get {
                return ResourceManager.GetString("DeleteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить/редактировать инструмент.
        /// </summary>
        public static string EditInsertInstrument {
            get {
                return ResourceManager.GetString("EditInsertInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить/редактировать студента.
        /// </summary>
        public static string EditInsertStudent {
            get {
                return ResourceManager.GetString("EditInsertStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить/редактировать предмет.
        /// </summary>
        public static string EditInsertSubject {
            get {
                return ResourceManager.GetString("EditInsertSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить/редактировать преподавателя.
        /// </summary>
        public static string EditInsertTeacher {
            get {
                return ResourceManager.GetString("EditInsertTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часов в неделю(1-й семестр).
        /// </summary>
        public static string FirstSemesterHoursPerWeekCount {
            get {
                return ResourceManager.GetString("FirstSemesterHoursPerWeekCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недель в 1-й семестр.
        /// </summary>
        public static string FirstSemesterWeeksCount {
            get {
                return ResourceManager.GetString("FirstSemesterWeeksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструмент.
        /// </summary>
        public static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструменты.
        /// </summary>
        public static string Instruments {
            get {
                return ResourceManager.GetString("Instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список инструментов.
        /// </summary>
        public static string InstrumentsList {
            get {
                return ResourceManager.GetString("InstrumentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип параметров.
        /// </summary>
        public static string ParametersType {
            get {
                return ResourceManager.GetString("ParametersType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить данные на форме.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание на семестр.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список расписаний предмета.
        /// </summary>
        public static string Schedules {
            get {
                return ResourceManager.GetString("Schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часов в неделю(2-й семестр).
        /// </summary>
        public static string SecondSemesterHoursPerWeekCount {
            get {
                return ResourceManager.GetString("SecondSemesterHoursPerWeekCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недель в 2-й семестр.
        /// </summary>
        public static string SecondSemesterWeeksCount {
            get {
                return ResourceManager.GetString("SecondSemesterWeeksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите курс.
        /// </summary>
        public static string SelectStudyYear {
            get {
                return ResourceManager.GetString("SelectStudyYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычные часы.
        /// </summary>
        public static string StandatdParameters {
            get {
                return ResourceManager.GetString("StandatdParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студент.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенты.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список студентов.
        /// </summary>
        public static string StudentsList {
            get {
                return ResourceManager.GetString("StudentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учебная программа.
        /// </summary>
        public static string StudyProgram {
            get {
                return ResourceManager.GetString("StudyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс.
        /// </summary>
        public static string StudyYear {
            get {
                return ResourceManager.GetString("StudyYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмет.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать предмет.
        /// </summary>
        public static string SubjectEdit {
            get {
                return ResourceManager.GetString("SubjectEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать предмет/Редактировать расписание.
        /// </summary>
        public static string SubjectEdit_ParameterEdit {
            get {
                return ResourceManager.GetString("SubjectEdit_ParameterEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать предмет/Добавить расписание.
        /// </summary>
        public static string SubjectEdit_ParameterInsert {
            get {
                return ResourceManager.GetString("SubjectEdit_ParameterInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить предмет.
        /// </summary>
        public static string SubjectInsert {
            get {
                return ResourceManager.GetString("SubjectInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить предмет/Добавить расписание.
        /// </summary>
        public static string SubjectInsert_ParameterInsert {
            get {
                return ResourceManager.GetString("SubjectInsert_ParameterInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предметы.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список предметов.
        /// </summary>
        public static string SubjectsList {
            get {
                return ResourceManager.GetString("SubjectsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нагрузка.
        /// </summary>
        public static string TeacherOverLoading {
            get {
                return ResourceManager.GetString("TeacherOverLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватели.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список преподавателей.
        /// </summary>
        public static string TeachersList {
            get {
                return ResourceManager.GetString("TeachersList", resourceCulture);
            }
        }
    }
}
